language: ruby
rvm:
  - 1.9.3
bundler_args: '--without development'
before_script:
  - "psql -c 'create database hackd_test;' -U postgres"
  - 'cp config/database.yml.example config/database.yml'
  - 'RAILS_ENV=test bundle exec rake db:migrate >> /dev/null 2>&1'
script:
  - 'RAILS_ENV=test bundle exec rake'
