github_key: &github_key
  token: ENV['GITHUB_TOKEN']
  key: ENV['GITHUB_KEY']
  organization: hackd

staging:
  <<: *github_key

development:
  <<: *github_key

production:
  <<: *github_key

test: 
  <<: *github_key
