github_key: &github_key
  token: your_token_id 
  key: your_key 
  organization: hackd

staging: 
  <<: *github_key

development: 
  <<: *github_key

production: 
  <<: *github_key

test: 
  <<: *github_key
